# need to install java > 1.6, and python antlr4 runtime https://pypi.python.org/pypi/antlr4-python2-runtime/

all:
	java -Xmx500M -cp "./antlr-4.5-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Python2 Lua.g4
